"""Seed data, ported from the frontend's src/data.ts."""

# Demo accounts. Passwords are hashed at seed time, never stored in plain text.
# These match the personas the login screen offers.
USERS = [
    {
        "user_id": "user-victoria",
        "email": "victoria@styleswap.com",
        "password": "password123",
        "name": "Victoria Fontaine",
        "phone": "+1 (555) 019-2834",
        "role": "customer",
        "profile_pic": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=150",
        "sustainability_score": 89,
        "reward_points": 1250,
        "tier": "Gold",
    },
    {
        "user_id": "user-cos",
        "email": "cos@styleswap.com",
        "password": "password123",
        "name": "Atelier COS Resell",
        "phone": "+1 (555) 442-1180",
        "role": "vendor",
        "profile_pic": "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=150",
        "sustainability_score": 100,
        "reward_points": 0,
        "tier": "Partner",
    },
    {
        "user_id": "user-admin",
        "email": "admin@styleswap.com",
        "password": "password123",
        "name": "System Administrator",
        "phone": "+1 (555) 000-0001",
        "role": "admin",
        "profile_pic": "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=150",
        "sustainability_score": 100,
        "reward_points": 0,
        "tier": "Partner",
    },
]

ADDRESSES = [
    {
        "address_id": "addr-1",
        "user_id": "user-victoria",
        "label": "Townhouse Residence (Default)",
        "street": "742 Fifth Avenue, Apt 4B",
        "city": "New York",
        "state": "NY",
        "zip": "10019",
        "is_default": True,
    },
    {
        "address_id": "addr-2",
        "user_id": "user-victoria",
        "label": "Summer Cottage",
        "street": "18 Dune Road",
        "city": "East Hampton",
        "state": "NY",
        "zip": "11937",
        "is_default": False,
    },
]

PRODUCTS = [
    {
        "product_id": "prod-1",
        "name": "Silk Halter Wedding Gown",
        "category": "Wedding",
        "sub_category": "Bridal Gowns",
        "brand": "L’Aura Bridal",
        "description": "An elegant, backless halter-neck gown draped in 100% heavy mulberry silk. Subtle cowl neckline, fluid court train, and seamless tailoring create an ethereal silhouette for the modern bride. Sourced sustainably with clean-washing certificates.",
        "image": "https://images.unsplash.com/photo-1594552072238-b8a33785b261?auto=format&fit=crop&q=80&w=600",
        "gallery": [
            "https://images.unsplash.com/photo-1594552072238-b8a33785b261?auto=format&fit=crop&q=80&w=600",
            "https://images.unsplash.com/photo-1518049362265-d5b2a6467637?auto=format&fit=crop&q=80&w=600",
        ],
        "sizes": ["XS", "S", "M", "L"],
        "colors": [
            {"name": "Alabaster White", "hex": "#FAF9F6"},
            {"name": "Champagne Cream", "hex": "#F3EED9"},
        ],
        "rental_price": 75,
        "security_deposit": 350,
        "vendor_name": "Aura Premium Archives",
        "vendor_user_id": None,
        "vendor_verified": "Trusted Vendor",
        "rating": 4.9,
        "reviews_count": 24,
        "badge": "Premium",
        "status": "Available",
        "delivery_date": "Tomorrow",
    },
    {
        "product_id": "prod-2",
        "name": "Textured Bouclé Blazer",
        "category": "Women",
        "sub_category": "Blazers & Jackets",
        "brand": "COS Premium",
        "description": "A tailored oversized blazer woven with a heavy, textured wool-blend bouclé. Features structured shoulders, slim notch lapels, and custom tortoiseshell buttons. Ideal for sophisticated daywear or formal meetings.",
        "image": "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&q=80&w=600",
        "gallery": [
            "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&q=80&w=600"
        ],
        "sizes": ["S", "M", "L", "XL"],
        "colors": [
            {"name": "Oatmeal Beige", "hex": "#E6DFD3"},
            {"name": "Off-White", "hex": "#FAF9F6"},
        ],
        "rental_price": 18,
        "security_deposit": 80,
        "vendor_name": "Atelier COS Resell",
        "vendor_user_id": "user-cos",
        "vendor_verified": "Verified Vendor",
        "rating": 4.7,
        "reviews_count": 18,
        "badge": "Trending",
        "status": "Available",
        "delivery_date": "In 2 days",
    },
    {
        "product_id": "prod-3",
        "name": "Linen Double-Breasted Suit",
        "category": "Men",
        "sub_category": "Suits",
        "brand": "Mango Man Tailoring",
        "description": "Unstructured double-breasted suit jacket crafted from breathable, luxury Italian flax linen. Features soft shoulders, peak lapels, and dual patch pockets for a relaxed yet highly tailored summer-smart aesthetic.",
        "image": "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&q=80&w=600",
        "gallery": [
            "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&q=80&w=600"
        ],
        "sizes": ["46 (S)", "48 (M)", "50 (L)", "52 (XL)"],
        "colors": [
            {"name": "Desert Sand", "hex": "#D2C5B4"},
            {"name": "Charcoal Slate", "hex": "#3A3A3A"},
        ],
        "rental_price": 28,
        "security_deposit": 120,
        "vendor_name": "Tailored Closet Co.",
        "vendor_user_id": None,
        "vendor_verified": "Verified Vendor",
        "rating": 4.8,
        "reviews_count": 15,
        "badge": "Bestseller",
        "status": "Available",
        "delivery_date": "In 3 days",
    },
    {
        "product_id": "prod-4",
        "name": "18K Gold Plated Arch Earrings",
        "category": "Jewellery",
        "sub_category": "Earrings",
        "brand": "Savoir Jewelry",
        "description": "Brutalist, architectural-inspired drop earrings. Cast in recycled sterling silver and hand-plated in heavy 18-karat yellow gold. Brushed satin finish reflecting subtle light. Ultra-lightweight for comfortable, secure wear.",
        "image": "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&q=80&w=600",
        "gallery": [
            "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&q=80&w=600"
        ],
        "sizes": ["One Size"],
        "colors": [{"name": "Brushed Gold", "hex": "#D4AF37"}],
        "rental_price": 12,
        "security_deposit": 50,
        "vendor_name": "Savoir Archives",
        "vendor_user_id": None,
        "vendor_verified": "Trusted Vendor",
        "rating": 4.9,
        "reviews_count": 31,
        "badge": "Customer Favorite",
        "status": "Available",
        "delivery_date": "Tomorrow",
    },
    {
        "product_id": "prod-5",
        "name": "Structured Minimalist Tote",
        "category": "Handbags",
        "sub_category": "Totes",
        "brand": "Aesop Atelier",
        "description": "A seamless, architectural handbag crafted from premium vegetable-tanned Italian calf leather. Unlined raw interior with a magnetic snap clasp and a delicate gold embossed stamp. Large enough for a laptop or portfolio.",
        "image": "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&q=80&w=600",
        "gallery": [
            "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&q=80&w=600"
        ],
        "sizes": ["Medium"],
        "colors": [
            {"name": "Warm Taupe", "hex": "#B8A898"},
            {"name": "Noir Black", "hex": "#232323"},
        ],
        "rental_price": 22,
        "security_deposit": 100,
        "vendor_name": "Aesop Leather Vault",
        "vendor_user_id": None,
        "vendor_verified": "Trusted Vendor",
        "rating": 4.6,
        "reviews_count": 14,
        "badge": "New",
        "status": "Available",
        "delivery_date": "In 2 days",
    },
    {
        "product_id": "prod-6",
        "name": "Suede Pointed Chelsea Boots",
        "category": "Shoes",
        "sub_category": "Boots",
        "brand": "Saint Laurent Style",
        "description": "Pointed-toe Chelsea boots crafted in Italy with premium sand-colored suede leather. Elastic side panels, premium leather soles, and a elegant tapered heel that elevates any tailoring outfit.",
        "image": "https://images.unsplash.com/photo-1520639888713-7851133b1ed0?auto=format&fit=crop&q=80&w=600",
        "gallery": [
            "https://images.unsplash.com/photo-1520639888713-7851133b1ed0?auto=format&fit=crop&q=80&w=600"
        ],
        "sizes": ["38", "39", "40", "41", "42"],
        "colors": [{"name": "Sand Suede", "hex": "#D3C6B8"}],
        "rental_price": 25,
        "security_deposit": 150,
        "vendor_name": "Le Premiere Rent",
        "vendor_user_id": None,
        "vendor_verified": "Trusted Vendor",
        "rating": 4.7,
        "reviews_count": 9,
        "badge": "Most Rented",
        "status": "Available",
        "delivery_date": "In 3 days",
    },
    {
        "product_id": "prod-7",
        "name": "Sculptural Ceramic Pottery Vase",
        "category": "Home Decoration",
        "sub_category": "Vases",
        "brand": "Studio Minimalist",
        "description": "A gorgeous handmade unglazed sandstone vase with a modern sculptural organic arch form. Captures warm shadow play and elevates luxury living spaces.",
        "image": "https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?auto=format&fit=crop&q=80&w=600",
        "gallery": [
            "https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?auto=format&fit=crop&q=80&w=600"
        ],
        "sizes": ["Regular"],
        "colors": [{"name": "Clay Sand", "hex": "#EFEBE4"}],
        "rental_price": 8,
        "security_deposit": 30,
        "vendor_name": "Clay & Craft Co.",
        "vendor_user_id": None,
        "vendor_verified": "Verified Vendor",
        "rating": 4.8,
        "reviews_count": 11,
        "badge": "New",
        "status": "Available",
        "delivery_date": "Tomorrow",
    },
    {
        "product_id": "prod-8",
        "name": "Chunky Knit Cashmere Throw",
        "category": "Home Decoration",
        "sub_category": "Throws",
        "brand": "Aesop Home",
        "description": "Ultra-heavy knit throw blanket spun from 100% grade-A Mongolian cashmere. Woven in neutral sand and cream hues with a tactile ribbed border. Impeccable weight and softness for luxurious home styling.",
        "image": "https://images.unsplash.com/photo-1580301762395-21ce84d00bc6?auto=format&fit=crop&q=80&w=600",
        "gallery": [
            "https://images.unsplash.com/photo-1580301762395-21ce84d00bc6?auto=format&fit=crop&q=80&w=600"
        ],
        "sizes": ["Queen Size"],
        "colors": [{"name": "Cream Cashmere", "hex": "#FAF8F4"}],
        "rental_price": 15,
        "security_deposit": 90,
        "vendor_name": "Aesop Home Archives",
        "vendor_user_id": None,
        "vendor_verified": "Trusted Vendor",
        "rating": 4.9,
        "reviews_count": 15,
        "badge": "Premium",
        "status": "Available",
        "delivery_date": "Tomorrow",
    },
    {
        "product_id": "prod-9",
        "name": "Organic Linen Child Romper",
        "category": "Kids",
        "sub_category": "Rompers",
        "brand": "COS Kids Premium",
        "description": "A soft, hypoallergenic romper woven in breathable organic linen. Features wooden buttons down the front, adjustable cross-back shoulder straps, and easy snap closures at the inseam. Beautiful minimalist neutral kidswear.",
        "image": "https://images.unsplash.com/photo-1522771930-78848d9293e8?auto=format&fit=crop&q=80&w=600",
        "gallery": [
            "https://images.unsplash.com/photo-1522771930-78848d9293e8?auto=format&fit=crop&q=80&w=600"
        ],
        "sizes": ["6-12M", "12-18M", "2Y", "3Y"],
        "colors": [{"name": "Oat Oatmeal", "hex": "#E9E3D8"}],
        "rental_price": 9,
        "security_deposit": 35,
        "vendor_name": "COS Kids Resell",
        "vendor_user_id": None,
        "vendor_verified": "Standard",
        "rating": 4.5,
        "reviews_count": 6,
        "badge": "New",
        "status": "Available",
        "delivery_date": "In 2 days",
    },
    {
        "product_id": "prod-10",
        "name": "Classic Structured Trench Coat",
        "category": "Men",
        "sub_category": "Coats & Jackets",
        "brand": "COS Tailored",
        "description": "A timeless, double-breasted trench coat tailored in high-density water-resistant organic cotton gabardine. Features a removable waist belt, horn-style buttons, deep epaulets, and a rear ventilation storm flap. Perfect layering piece.",
        "image": "https://images.unsplash.com/photo-1617137968427-85924c800a22?auto=format&fit=crop&q=80&w=600",
        "gallery": [
            "https://images.unsplash.com/photo-1617137968427-85924c800a22?auto=format&fit=crop&q=80&w=600"
        ],
        "sizes": ["48 (M)", "50 (L)", "52 (XL)"],
        "colors": [
            {"name": "Classic Caramel", "hex": "#C2A782"},
            {"name": "Slate Shadow", "hex": "#4E4E4E"},
        ],
        "rental_price": 24,
        "security_deposit": 110,
        "vendor_name": "Atelier COS Resell",
        "vendor_user_id": "user-cos",
        "vendor_verified": "Verified Vendor",
        "rating": 4.8,
        "reviews_count": 11,
        "badge": "Trending",
        "status": "Available",
        "delivery_date": "In 2 days",
    },
]

REVIEWS = [
    {
        "review_id": "rev-1",
        "product_id": "prod-1",
        "user_id": "user-victoria",
        "user_name": "Eleanor Vance",
        "user_avatar": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=100",
        "rating": 5,
        "comment": "Wore this for my pre-wedding shoot. Absolute perfection, the drape is incredible and feels incredibly luxurious. Returning it was seamless.",
        "date": "2026-06-25",
        "variant": "XS / Alabaster White",
    },
    {
        "review_id": "rev-2",
        "product_id": "prod-2",
        "user_id": "user-victoria",
        "user_name": "Sofia Martinez",
        "user_avatar": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=100",
        "rating": 5,
        "comment": "Excellent quality. Loved the oversized silhouette. Pairs beautifully with wide-leg trousers.",
        "date": "2026-07-01",
        "variant": "M / Oatmeal Beige",
    },
    {
        "review_id": "rev-3",
        "product_id": "prod-3",
        "user_id": "user-victoria",
        "user_name": "Alistair G.",
        "user_avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=100",
        "rating": 5,
        "comment": "Fit was exactly as estimated by the AI Size tool. Crisp fabric, perfect for a vineyard wedding.",
        "date": "2026-06-18",
        "variant": "48 (M) / Desert Sand",
    },
    {
        "review_id": "rev-4",
        "product_id": "prod-4",
        "user_id": "user-victoria",
        "user_name": "Chloe Bennet",
        "user_avatar": "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=100",
        "rating": 5,
        "comment": "Breathtakingly minimal. Added just the right amount of sophistication to my simple linen dress.",
        "date": "2026-07-05",
        "variant": "One Size / Brushed Gold",
    },
]

COUPONS = [
    {
        "code": "STYLE20",
        "discount_type": "percentage",
        "value": 20,
        "description": "20% off your entire rental order",
    },
    {
        "code": "ECOLUXE",
        "discount_type": "fixed",
        "value": 15,
        "description": "₹15 off for high sustainability rating",
    },
    {
        "code": "FIRSTSWAP",
        "discount_type": "fixed",
        "value": 10,
        "description": "₹10 discount on your first rental",
    },
]

NOTIFICATIONS = [
    {
        "notification_id": "not-1",
        "user_id": "user-victoria",
        "title": "Upcoming Return Reminder",
        "message": "Your rental 'Textured Bouclé Blazer' is due back in 2 days. Secure return pickup is scheduled for Wednesday.",
        "type": "return",
        "date": "1 hour ago",
        "read": False,
    },
    {
        "notification_id": "not-2",
        "user_id": "user-victoria",
        "title": "AI Stylist Recommendation",
        "message": "Based on your interest in beige blazers, our AI Stylist generated a custom look for your upcoming 'Gallery Opening' event.",
        "type": "ai",
        "date": "4 hours ago",
        "read": False,
    },
    {
        "notification_id": "not-3",
        "user_id": "user-victoria",
        "title": "Delivery Successfully Dispatched",
        "message": "Your '18K Gold Plated Arch Earrings' have left the Savior Jewelry archive. Tracking details inside.",
        "type": "delivery",
        "date": "Yesterday",
        "read": True,
    },
    {
        "notification_id": "not-4",
        "user_id": "user-victoria",
        "title": "Ecoluxe Sustainability Milestone",
        "message": "Congratulations! You saved 4.2kg of textile waste and 14,000 liters of water this month by opting to swap instead of buy.",
        "type": "promo",
        "date": "3 days ago",
        "read": True,
    },
]
